/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnknownRouteImport } from './routes/_unknown'
import { Route as rootRouteRouteImport } from './routes/(root)/route'
import { Route as authorizedRouteRouteImport } from './routes/(authorized)/route'
import { Route as rootIndexRouteImport } from './routes/(root)/index'
import { Route as rootFeaturesRouteImport } from './routes/(root)/features'
import { Route as rootAboutRouteImport } from './routes/(root)/about'
import { Route as authorizedSimulationRouteRouteImport } from './routes/(authorized)/simulation/route'
import { Route as authorizedDashboardRouteRouteImport } from './routes/(authorized)/dashboard/route'
import { Route as authorizedDashboardIndexRouteImport } from './routes/(authorized)/dashboard/index'
import { Route as rootAuthSignupRouteImport } from './routes/(root)/auth/signup'
import { Route as rootAuthLoginRouteImport } from './routes/(root)/auth/login'
import { Route as authorizedSimulationScenarioIdRouteImport } from './routes/(authorized)/simulation/$scenarioId'
import { Route as authorizedDashboardUploadRouteImport } from './routes/(authorized)/dashboard/upload'
import { Route as authorizedDashboardSettingsRouteImport } from './routes/(authorized)/dashboard/settings'
import { Route as authorizedDashboardScenariosRouteImport } from './routes/(authorized)/dashboard/scenarios'
import { Route as authorizedDashboardProgressRouteImport } from './routes/(authorized)/dashboard/progress'

const UnknownRoute = UnknownRouteImport.update({
  id: '/_unknown',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRouteRoute = rootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedRouteRoute = authorizedRouteRouteImport.update({
  id: '/(authorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const rootIndexRoute = rootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootFeaturesRoute = rootFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootAboutRoute = rootAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteRoute,
} as any)
const authorizedSimulationRouteRoute =
  authorizedSimulationRouteRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => authorizedRouteRoute,
  } as any)
const authorizedDashboardRouteRoute =
  authorizedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authorizedRouteRoute,
  } as any)
const authorizedDashboardIndexRoute =
  authorizedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authorizedDashboardRouteRoute,
  } as any)
const rootAuthSignupRoute = rootAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootAuthLoginRoute = rootAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteRoute,
} as any)
const authorizedSimulationScenarioIdRoute =
  authorizedSimulationScenarioIdRouteImport.update({
    id: '/$scenarioId',
    path: '/$scenarioId',
    getParentRoute: () => authorizedSimulationRouteRoute,
  } as any)
const authorizedDashboardUploadRoute =
  authorizedDashboardUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => authorizedDashboardRouteRoute,
  } as any)
const authorizedDashboardSettingsRoute =
  authorizedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authorizedDashboardRouteRoute,
  } as any)
const authorizedDashboardScenariosRoute =
  authorizedDashboardScenariosRouteImport.update({
    id: '/scenarios',
    path: '/scenarios',
    getParentRoute: () => authorizedDashboardRouteRoute,
  } as any)
const authorizedDashboardProgressRoute =
  authorizedDashboardProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => authorizedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof rootIndexRoute
  '/dashboard': typeof authorizedDashboardRouteRouteWithChildren
  '/simulation': typeof authorizedSimulationRouteRouteWithChildren
  '/about': typeof rootAboutRoute
  '/features': typeof rootFeaturesRoute
  '/dashboard/progress': typeof authorizedDashboardProgressRoute
  '/dashboard/scenarios': typeof authorizedDashboardScenariosRoute
  '/dashboard/settings': typeof authorizedDashboardSettingsRoute
  '/dashboard/upload': typeof authorizedDashboardUploadRoute
  '/simulation/$scenarioId': typeof authorizedSimulationScenarioIdRoute
  '/auth/login': typeof rootAuthLoginRoute
  '/auth/signup': typeof rootAuthSignupRoute
  '/dashboard/': typeof authorizedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof rootIndexRoute
  '/simulation': typeof authorizedSimulationRouteRouteWithChildren
  '/about': typeof rootAboutRoute
  '/features': typeof rootFeaturesRoute
  '/dashboard/progress': typeof authorizedDashboardProgressRoute
  '/dashboard/scenarios': typeof authorizedDashboardScenariosRoute
  '/dashboard/settings': typeof authorizedDashboardSettingsRoute
  '/dashboard/upload': typeof authorizedDashboardUploadRoute
  '/simulation/$scenarioId': typeof authorizedSimulationScenarioIdRoute
  '/auth/login': typeof rootAuthLoginRoute
  '/auth/signup': typeof rootAuthSignupRoute
  '/dashboard': typeof authorizedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authorized)': typeof authorizedRouteRouteWithChildren
  '/(root)': typeof rootRouteRouteWithChildren
  '/_unknown': typeof UnknownRoute
  '/(authorized)/dashboard': typeof authorizedDashboardRouteRouteWithChildren
  '/(authorized)/simulation': typeof authorizedSimulationRouteRouteWithChildren
  '/(root)/about': typeof rootAboutRoute
  '/(root)/features': typeof rootFeaturesRoute
  '/(root)/': typeof rootIndexRoute
  '/(authorized)/dashboard/progress': typeof authorizedDashboardProgressRoute
  '/(authorized)/dashboard/scenarios': typeof authorizedDashboardScenariosRoute
  '/(authorized)/dashboard/settings': typeof authorizedDashboardSettingsRoute
  '/(authorized)/dashboard/upload': typeof authorizedDashboardUploadRoute
  '/(authorized)/simulation/$scenarioId': typeof authorizedSimulationScenarioIdRoute
  '/(root)/auth/login': typeof rootAuthLoginRoute
  '/(root)/auth/signup': typeof rootAuthSignupRoute
  '/(authorized)/dashboard/': typeof authorizedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/simulation'
    | '/about'
    | '/features'
    | '/dashboard/progress'
    | '/dashboard/scenarios'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/simulation/$scenarioId'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/simulation'
    | '/about'
    | '/features'
    | '/dashboard/progress'
    | '/dashboard/scenarios'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/simulation/$scenarioId'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard'
  id:
    | '__root__'
    | '/(authorized)'
    | '/(root)'
    | '/_unknown'
    | '/(authorized)/dashboard'
    | '/(authorized)/simulation'
    | '/(root)/about'
    | '/(root)/features'
    | '/(root)/'
    | '/(authorized)/dashboard/progress'
    | '/(authorized)/dashboard/scenarios'
    | '/(authorized)/dashboard/settings'
    | '/(authorized)/dashboard/upload'
    | '/(authorized)/simulation/$scenarioId'
    | '/(root)/auth/login'
    | '/(root)/auth/signup'
    | '/(authorized)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authorizedRouteRoute: typeof authorizedRouteRouteWithChildren
  rootRouteRoute: typeof rootRouteRouteWithChildren
  UnknownRoute: typeof UnknownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unknown': {
      id: '/_unknown'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnknownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)': {
      id: '/(root)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)': {
      id: '/(authorized)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/features': {
      id: '/(root)/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof rootFeaturesRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/about': {
      id: '/(root)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof rootAboutRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(authorized)/simulation': {
      id: '/(authorized)/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof authorizedSimulationRouteRouteImport
      parentRoute: typeof authorizedRouteRoute
    }
    '/(authorized)/dashboard': {
      id: '/(authorized)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authorizedDashboardRouteRouteImport
      parentRoute: typeof authorizedRouteRoute
    }
    '/(authorized)/dashboard/': {
      id: '/(authorized)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authorizedDashboardIndexRouteImport
      parentRoute: typeof authorizedDashboardRouteRoute
    }
    '/(root)/auth/signup': {
      id: '/(root)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof rootAuthSignupRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/auth/login': {
      id: '/(root)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof rootAuthLoginRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(authorized)/simulation/$scenarioId': {
      id: '/(authorized)/simulation/$scenarioId'
      path: '/$scenarioId'
      fullPath: '/simulation/$scenarioId'
      preLoaderRoute: typeof authorizedSimulationScenarioIdRouteImport
      parentRoute: typeof authorizedSimulationRouteRoute
    }
    '/(authorized)/dashboard/upload': {
      id: '/(authorized)/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof authorizedDashboardUploadRouteImport
      parentRoute: typeof authorizedDashboardRouteRoute
    }
    '/(authorized)/dashboard/settings': {
      id: '/(authorized)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof authorizedDashboardSettingsRouteImport
      parentRoute: typeof authorizedDashboardRouteRoute
    }
    '/(authorized)/dashboard/scenarios': {
      id: '/(authorized)/dashboard/scenarios'
      path: '/scenarios'
      fullPath: '/dashboard/scenarios'
      preLoaderRoute: typeof authorizedDashboardScenariosRouteImport
      parentRoute: typeof authorizedDashboardRouteRoute
    }
    '/(authorized)/dashboard/progress': {
      id: '/(authorized)/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof authorizedDashboardProgressRouteImport
      parentRoute: typeof authorizedDashboardRouteRoute
    }
  }
}

interface authorizedDashboardRouteRouteChildren {
  authorizedDashboardProgressRoute: typeof authorizedDashboardProgressRoute
  authorizedDashboardScenariosRoute: typeof authorizedDashboardScenariosRoute
  authorizedDashboardSettingsRoute: typeof authorizedDashboardSettingsRoute
  authorizedDashboardUploadRoute: typeof authorizedDashboardUploadRoute
  authorizedDashboardIndexRoute: typeof authorizedDashboardIndexRoute
}

const authorizedDashboardRouteRouteChildren: authorizedDashboardRouteRouteChildren =
  {
    authorizedDashboardProgressRoute: authorizedDashboardProgressRoute,
    authorizedDashboardScenariosRoute: authorizedDashboardScenariosRoute,
    authorizedDashboardSettingsRoute: authorizedDashboardSettingsRoute,
    authorizedDashboardUploadRoute: authorizedDashboardUploadRoute,
    authorizedDashboardIndexRoute: authorizedDashboardIndexRoute,
  }

const authorizedDashboardRouteRouteWithChildren =
  authorizedDashboardRouteRoute._addFileChildren(
    authorizedDashboardRouteRouteChildren,
  )

interface authorizedSimulationRouteRouteChildren {
  authorizedSimulationScenarioIdRoute: typeof authorizedSimulationScenarioIdRoute
}

const authorizedSimulationRouteRouteChildren: authorizedSimulationRouteRouteChildren =
  {
    authorizedSimulationScenarioIdRoute: authorizedSimulationScenarioIdRoute,
  }

const authorizedSimulationRouteRouteWithChildren =
  authorizedSimulationRouteRoute._addFileChildren(
    authorizedSimulationRouteRouteChildren,
  )

interface authorizedRouteRouteChildren {
  authorizedDashboardRouteRoute: typeof authorizedDashboardRouteRouteWithChildren
  authorizedSimulationRouteRoute: typeof authorizedSimulationRouteRouteWithChildren
}

const authorizedRouteRouteChildren: authorizedRouteRouteChildren = {
  authorizedDashboardRouteRoute: authorizedDashboardRouteRouteWithChildren,
  authorizedSimulationRouteRoute: authorizedSimulationRouteRouteWithChildren,
}

const authorizedRouteRouteWithChildren = authorizedRouteRoute._addFileChildren(
  authorizedRouteRouteChildren,
)

interface rootRouteRouteChildren {
  rootAboutRoute: typeof rootAboutRoute
  rootFeaturesRoute: typeof rootFeaturesRoute
  rootIndexRoute: typeof rootIndexRoute
  rootAuthLoginRoute: typeof rootAuthLoginRoute
  rootAuthSignupRoute: typeof rootAuthSignupRoute
}

const rootRouteRouteChildren: rootRouteRouteChildren = {
  rootAboutRoute: rootAboutRoute,
  rootFeaturesRoute: rootFeaturesRoute,
  rootIndexRoute: rootIndexRoute,
  rootAuthLoginRoute: rootAuthLoginRoute,
  rootAuthSignupRoute: rootAuthSignupRoute,
}

const rootRouteRouteWithChildren = rootRouteRoute._addFileChildren(
  rootRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authorizedRouteRoute: authorizedRouteRouteWithChildren,
  rootRouteRoute: rootRouteRouteWithChildren,
  UnknownRoute: UnknownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
